# Generated by Django 4.2.11 on 2024-03-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='ip_address',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
