# Generated by Django 4.2.11 on 2024-03-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_click_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
